# Multiple Linear Regression

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('Book1.csv')

In [4]:
data

area  bedroom   age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [9]:
data.columns

Index(['area', 'bedroom ', 'age', 'price'], dtype='object')

In [17]:
import math
median_bedrooms = math.floor(data['bedroom '].median())

In [21]:
data['bedroom '] = data['bedroom '].fillna(median_bedrooms)

In [22]:
data

area  bedroom   age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [28]:
data = data.rename(columns = {'bedroom ':'bedrooms'})

In [29]:
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [23]:
from sklearn import linear_model

In [30]:
reg = linear_model.LinearRegression()

reg.fit(data[['area','bedrooms', 'age']],data.price)

LinearRegression()

In [31]:
reg.intercept_

383724.99999999994

In [35]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [41]:
reg.predict([[2500,4,5]])

F:\Python 38\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])

In [42]:
price = 137.25*3000+(-26025*3)+(-6825.*15)+383724.99999999994
price

615025.0

# EXERCISE 

In [43]:
df = pd.read_csv('Book2.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)  \
0        NaN                    8.0                           9      50000   
1        NaN                    8.0                           6      45000   
2       five                    6.0                           7      60000   
3        two                   10.0                          10      65000   
4      seven                    9.0                           6      70000   
5      three                    7.0                          10      62000   
6        ten                    NaN                           7      72000   
7     eleven                    7.0                           8      80000   

   Unnamed: 4  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
4         NaN  
5         NaN  
6         NaN  
7         NaN

In [58]:
df.experience = df.experience.fillna('Zero')

In [47]:
from word2number import w2n

In [59]:
exp = []
for i in df.experience:
    exp.append(w2n.word_to_num(i))

In [61]:
df.experience = exp

In [62]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)  \
0           0                    8.0                           9      50000   
1           0                    8.0                           6      45000   
2           5                    6.0                           7      60000   
3           2                   10.0                          10      65000   
4           7                    9.0                           6      70000   
5           3                    7.0                          10      62000   
6          10                    NaN                           7      72000   
7          11                    7.0                           8      80000   

   Unnamed: 4  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
4         NaN  
5         NaN  
6         NaN  
7         NaN

In [64]:
test_median = math.floor(df['test_score(out of 10)'].median())

In [65]:
test_median

8

In [71]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(test_median)

In [66]:
interview_median = math.floor(df['interview_score(out of 10)'].median())

In [67]:
interview_median

7

In [72]:
df['interview_score(out of 10)'] = df['interview_score(out of 10)'].fillna(interview_median)

In [68]:
df.drop('Unnamed: 4', axis = 1, inplace = True)

In [73]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [74]:
reg_1 = linear_model.LinearRegression()

In [76]:
reg_1.fit(df[['experience','test_score(out of 10)', 'interview_score(out of 10)']], df['salary($)'])

LinearRegression()

In [81]:
reg_1.predict([[12,10,10]])

F:\Python 38\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])

In [82]:
reg_1.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [83]:
reg_1.intercept_

17737.263464337688