In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

## Logistic Regression

In [23]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.95

## SVM

In [24]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.4

## Random Forest

In [25]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9740740740740741

# K-Fold Cross Validation

In [28]:
from sklearn.model_selection import KFold

In [35]:
kf = KFold(n_splits=3)

In [36]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [37]:
def get_score(model, X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [39]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9833333333333333

In [42]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

F:\Python 38\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

In [43]:
from sklearn.model_selection import StratifiedKFold

In [44]:
folds = StratifiedKFold(n_splits=3)

In [60]:
scores_logistic = []
scores_svm = []
scores_rf = []

In [61]:
for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [62]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [63]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [64]:
scores_rf

[0.9315525876460768, 0.9398998330550918, 0.9165275459098498]

## Cross Val Score 

In [65]:
from sklearn.model_selection import cross_val_score

In [66]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [67]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [68]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.92821369, 0.95492487, 0.92320534])

## Parameter Tuning

In [76]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8781346989447547

In [77]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9421260086902544

In [78]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.948261949099938

In [79]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9409931719428926

In [80]:
scores5 = cross_val_score(RandomForestClassifier(n_estimators=50),digits.data, digits.target, cv=10)
np.average(scores5)

0.9421229050279329

In [81]:
scores6 = cross_val_score(RandomForestClassifier(n_estimators=60),digits.data, digits.target, cv=10)
np.average(scores6)

0.9493606455617627

# Exercise

In [82]:
from sklearn.datasets import load_iris

In [83]:
iris = load_iris()

In [84]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [96]:
from sklearn.model_selection import cross_val_score

In [97]:
l_scores = cross_val_score(LogisticRegression(),iris.data,iris.target,cv=4)
l_scores

F:\Python 38\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.97368421, 0.97368421, 0.94594595, 1.        ])

In [98]:
np.average(l_scores)

0.9733285917496444

In [99]:
s_scores = cross_val_score(SVC(),iris.data,iris.target,cv=4)
s_scores

array([0.97368421, 1.        , 0.94594595, 0.97297297])

In [100]:
np.average(s_scores)

0.9731507823613088

In [101]:
r_scores = cross_val_score(RandomForestClassifier(),iris.data,iris.target,cv=4)

In [102]:
r_scores

array([0.97368421, 0.94736842, 0.94594595, 1.        ])

In [103]:
np.average(r_scores)

0.9667496443812233

**LogisticRegression is the best Algorithm to use here**