# Saving Model to File

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('Book1.csv')
data

area   Price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
from sklearn import linear_model

In [4]:
reg = linear_model.LinearRegression()

In [5]:
reg.fit(data[['area']], data.Price)

LinearRegression()

In [6]:
reg.predict([[5000]])

F:\Python 38\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

### Saving Model To file

##### Approach Number 1: Using Pickle

In [7]:
import pickle

In [8]:
with open('model_pickle', 'wb') as f:
    pickle.dump(reg,f)

In [9]:
with open('model_pickle', 'rb') as f:
    model = pickle.load(f)

In [10]:
model.predict([[5000]])

F:\Python 38\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

##### Approach Number 2: Using Joblib of Sklearn

*We Use Joblib generaly when we have huge numpy array*

In [13]:
import joblib

In [14]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [15]:
mod = joblib.load('model_joblib')

In [17]:
mod.coef_

array([135.78767123])